### ISSUE TITLE
Error: The `set_trainer` method must be called before calling `train`

### ISSUE THREAD

**Issue by sonnylaskar** [gunthercox/django_chatterbot#5]
Hi,

I just started exploring this.
I have Python 2.7.11, Django 1.9.7, Chatterbot 0.4.3.
I downloaded the code and when I run **python manage.py migrate**
I get the below error trace:

```
$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 398, in execute
    self.check()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/django-projects/django_chatterbot-master/example/example_app/urls.py", line 25, in <module>
    url(r'^api/chatterbot/', include('django_chatterbot.urls', namespace='chatterbot')),
  File "/usr/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 52, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/django-projects/django_chatterbot-master/example/django_chatterbot/urls.py", line 3, in <module>
    from django_chatterbot.api import ChatterBotView
  File "/opt/django-projects/django_chatterbot-master/example/django_chatterbot/api.py", line 11, in <module>
    chatterbot.train([
  File "/usr/local/lib/python2.7/site-packages/chatterbot/chatterbot.py", line 167, in train
    raise self.TrainerInitializationException()
chatterbot.chatterbot.TrainerInitializationException/usr/local/lib/python2.7/site-packages/chatterbot/chatterbot.py:185: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  return self.message

: The `set_trainer` method must be called before calling `train`.

```
Please assist

**Comment by gunthercox** [comment]
Hi @sonnylaskar,

Lets take a look at the last couple lines of the traceback that you got for this error. 

The first thing that I noticed was that the exception being raised is a `TrainerInitializationException` and that this is happening in `"/opt/django-projects/django_chatterbot-master/example/django_chatterbot/api.py"` on line 11. I figured this out by reading this line from the traceback:

```
  File "/opt/django-projects/django_chatterbot-master/example/django_chatterbot/api.py", line 11, in <module>
    chatterbot.train([
  File "/usr/local/lib/python2.7/site-packages/chatterbot/chatterbot.py", line 167, in train
    raise self.TrainerInitializationException()
```

So, I opened up the [`api.py`](https://github.com/gunthercox/django_chatterbot/blob/master/example/django_chatterbot/api.py) file and noticed that the `train` method was being called, but the `set_trainer` method was not. This makes sense considering that the message returned by this exception says `The 'set_trainer' method must be called before calling 'train'`.

There is also a section in ChatterBot's documentation that covers this (http://chatterbot.readthedocs.io/en/latest/training.html#setting-the-training-class), but essentially what this error message means is that the `set_trainer` method needs to be called before the `train` method so that the chat bot can process the data that is passed to the `train` method. ChatterBot allows for custom trainer classes to be created so that it can be trained via different data formats when needed.

You should be all set now, I have edited the `api.py` file to call the `set_trainer` method before calling the `train` method. You can see the changes I made in this commit: https://github.com/gunthercox/django_chatterbot/commit/0bda658447458acb9fdf0f8dd7383d2bf39fb37b
